### ISSUE TITLE
`muteReconfirmation_timestamp` timestamp NULL default 'NULL'

### ISSUE THREAD

**Issue by toblinga** [foodsoft/foodsoft#10]
bei default schreibt man das NULL ohne hochkomma.

habe die tabelle selber erstellt, jetzt meckert er dass der default-value nicht 'NULL' ist

**Comment by tvogel** [comment]
Dito, ich hab hier:

```
ALTER TABLE `sessions` ADD COLUMN `muteReconfirmation_timestamp` timestamp null default null
```

Woher kommt Dein Code?

**Comment by toblinga** [comment]
hab beim Tabellen anlegen den fehler bekommen mit den 'NULL' daher hab ich dann die Tabelle manuell angelegt, und die Hochkommas beim NULL weggelassen. 
Nun meckert er im setup.php dass der defaultwert nicht richtig ist, und möchte folgendes SQL ausführen:
 ALTER TABLE sessions MODIFY COLUMN `muteReconfirmation_timestamp` timestamp NULL default 'NULL' ;
==> geht aber nicht.

Die Tabelle schaut in der Datenbank so aus, also wäre der NULL wert bereits drinnen => Nichts falsch:

```
mysql> describe sessions;
+------------------------------+-------------+------+-----+-------------------+----------------+
| Field                        | Type        | Null | Key | Default           | Extra          |
+------------------------------+-------------+------+-----+-------------------+----------------+
| id                           | int(11)     | NO   | PRI | NULL              | auto_increment |
| cookie                       | varchar(10) | NO   |     | NULL              |                |
| login_gruppen_id             | int(11)     | NO   |     | 0                 |                |
| dienst                       | tinyint(1)  | NO   |     | 0                 |                |
| dienstkontrollblatt_id       | int(11)     | NO   |     | 0                 |                |
| session_timestamp            | timestamp   | NO   |     | CURRENT_TIMESTAMP |                |
| muteReconfirmation_timestamp | timestamp   | YES  |     | NULL              |                |
+------------------------------+-------------+------+-----+-------------------+----------------+
```

Mir ist aufgefallen, dass das der einzige NULL-Dafault-Value ist. Kann es sein, dass das Update-Script damit nicht umgehen kann, weil bei einem Default-Sring-Value werden die Hochkommas natürlich benötigt

**Comment by toblinga** [comment]
Update: eine erweiterung der Funktion escape_val bringt auch nichts :(

```
function escape_val( $val ) {
  switch( $val ) {
    case 'CURRENT_TIMESTAMP';
      return $val;
    case 'NULL';
      return $val;
    case 'null';
      return $val;
    default:
      return "'$val'";
  }
}
```

**Comment by timof** [comment]
On Tue, Sep 10, 2013 at 12:41:38PM -0700, toblinga wrote:

> habe die tabelle selber erstellt, jetzt meckert er dass der default-value nicht 'NULL' ist

ja, das waere dann wohl der String "NULL" und nicht NULL, also nicht das
gewuenschte. Mit 'default' => '' kriegt man aber per default NULL als 
default. Ist jetzt auch so in stable, danke!

lg, Timo

**Comment by toblinga** [comment]
hab die änderung bei mir manuell gamacht nicht mit der neuen stable getestet. close es trotzem

Danke für die schnelle Reaktion!

LG
Armin
