### ISSUE TITLE
welche php-version wird unterstützt

### ISSUE THREAD

**Issue by toblinga** [foodsoft/foodsoft#11]
Hallo,
sorry ist kein bug, aber ich fand keine möglichkeit euch anderweitig zu kontaktieren.

auf welcher php-version basiert der code, da ich nach dem setup von einem fehler in den anderen stolpere, frag ich lieber mal nach.

Danke euch und lg
armin

**Comment by toblinga** [comment]
um genauer zu sein:
1. Fehler (apache error.log);

[Wed Sep 11 19:28:06 2013] [error] [client 83.64.62.50] PHP Fatal error:  Call-time pass-by-reference has been removed in /var/www/klappertopf.at/foodsoft/code/zuordnen.php on line 4857

nach dem ich die Zeile ausbesserte

exec( 'pdflatex tex2pdf.tex', & $output, & $rv ); => exec( 'pdflatex tex2pdf.tex', $output, $rv ); 

dann Fehler 2+ (apache error.log);
[Wed Sep 11 19:40:22 2013] [error] [client 83.64.62.50] PHP Notice:  Array to string conversion in /var/www/klappertopf.at/foodsoft/code/err_functions.php on line 19

und im Browser kam eine Fehler-Box:

[EinfÃ¼gen in Tabelle leitvariable fehlgeschlagen: 
  query: INSERT INTO leitvariable (  name, value, comment ) VALUES (  'member_showcase_count', '3', 'Anzahl an Mitgliedern, die auf der Startseite angezeigt werden (neben Schwarzem Brett)' )
  MySQL-error: Duplicate entry 'member_showcase_count' for key 'PRIMARY']
array (
  0 => 
  array (
    'file' => '/var/www/klappertopf.at/foodsoft/code/zuordnen.php',
    'line' => 51,
    'function' => 'error',
    'args' => 
    array (
      0 => 'EinfÃ¼gen in Tabelle leitvariable fehlgeschlagen: 
  query: INSERT INTO leitvariable (  name, value, comment ) VALUES (  \'member_showcase_count\', \'3\', \'Anzahl an Mitgliedern, die auf der Startseite angezeigt werden (neben Schwarzem Brett)\' )
  MySQL-error: Duplicate entry \'member_showcase_count\' for key \'PRIMARY\'',
    ),
  ),
  1 => 
  array (
    'file' => '/var/www/klappertopf.at/foodsoft/code/zuordnen.php',
    'line' => 233,
    'function' => 'doSql',
    'args' => 
    array (
      0 => 'INSERT INTO leitvariable (  name, value, comment ) VALUES (  \'member_showcase_count\', \'3\', \'Anzahl an Mitgliedern, die auf der Startseite angezeigt werden (neben Schwarzem Brett)\' )',
      1 => 2,
      2 => 'EinfÃ¼gen in Tabelle leitvariable fehlgeschlagen: ',
    ),
  ),
  2 => 
  array (
    'file' => '/var/www/klappertopf.at/foodsoft/code/zuordnen.php',
    'line' => 4730,
    'function' => 'sql_insert',
    'args' => 
    array (
      0 => 'leitvariable',
      1 => 
      array (
        'name' => 'member_showcase_count',
        'value' => '3',
        'comment' => 'Anzahl an Mitgliedern, die auf der Startseite angezeigt werden (neben Schwarzem Brett)',
      ),
    ),
  ),
  3 => 
  array (
    'file' => '/var/www/klappertopf.at/foodsoft/code/common.php',
    'line' => 95,
    'function' => 'update_database',
    'args' => 
    array (
      0 => '26',
    ),
  ),
  4 => 
  array (
    'file' => '/var/www/klappertopf.at/foodsoft/index.php',
    'line' => 5,
    'args' => 
    array (
      0 => '/var/www/klappertopf.at/foodsoft/code/common.php',
    ),
    'function' => 'require_once',
  ),
)

**Comment by timof** [comment]
On Wed, Sep 11, 2013 at 10:43:48AM -0700, toblinga wrote:

> [Wed Sep 11 19:28:06 2013] [error] [client 83.64.62.50] PHP Fatal error:  Call-time pass-by-reference has been removed in /var/www/klappertopf.at/foodsoft/code/zuordnen.php on line 4857

Ok ... das gab bisher hoechstens Warnungen. Hab die & auskommentiert, die 
stehen da nur als Doku drin.

> dann Fehler 2+ (apache error.log);
> [Wed Sep 11 19:40:22 2013] [error] [client 83.64.62.50] PHP Notice:  Array to string conversion in /var/www/klappertopf.at/foodsoft/code/err_functions.php on line 19

Eher harmlos, ist jetzt korrigiert.

> und im Browser kam eine Fehler-Box:
> 
> [Einf????gen in Tabelle leitvariable fehlgeschlagen: 
>   query: INSERT INTO leitvariable (  name, value, comment ) VALUES (  'member_showcase_count', '3', 'Anzahl an Mitgliedern, die auf der Startseite angezeigt werden (neben Schwarzem Brett)' )
>   MySQL-error: Duplicate entry 'member_showcase_count' for key 'PRIMARY']
> array (

Das ist auch weniger schlimm als es vielleicht aussieht: er versucht, die
Datenbank von Version 26 auf 27 zu bringen. Die ist aber bereits bei 28
(wird so vom setup.php erzeugt), wurde nur leider noch in `leitvariable`
mit 26 initialisiert. ist korrigiert.
Du kannst einfach die gespeicherte database_version auf 28 hochsetzen
(z.B. mit setup.php), dann sollte das weg sein!

Gruesse und viel Erfolg,
Timo
