### ISSUE TITLE
Lizenz eurer Software?

### ISSUE THREAD

**Issue by eliasmagn** [foodsoft/foodsoft#21]
Da wir diese Software nun in Lehnin verwenden, würde ich gerne wissen ob ihr sie unter GPL oder ähnliches stellen wollt, wenn ja, welche wäre es? Oder habe ich sie gar übersehen? Vielen Dank und mit beste Grüße aus Lehnin. 
Elias

**Comment by timof** [comment]
Hi Elias,
schoen dass ihr die foodsoft auch nutzt! ja, GPL hatte ich eigentlich immer gedacht, steht das noch nirgends? Ich bin da nicht ganz auf dem laufenden, hast du einen Vorschlag? Jedenfalls solllte sie fuer foodcoops frei nutzbar sein.
PS: deinen letzten patch hab ich aufgenommen, ohne test - soweit ich sehe sollte sich ja bei routbaren IPs nichts aendern. Allerdings: - geht setup.php jetzt noch von einer internen IP wie 10.x.x.x., die nutze ich gern fuer interne Zwecke im LAN?

**Comment by eliasmagn** [comment]
Ja verwendet die Remote Adresse wenn kein Proxieheader angegeben wird.

**Comment by eliasmagn** [comment]
Vieleicht die AGPL?
Gruß Elias

**Comment by tvogel** [comment]
Sieht für mich vernünftig aus. Die Frage ist, ob dann eine Download-Option gleich mit in die Food-Soft eingebaut werden sollte/müsste. Ich hab durchaus zeitweise mal lokal was gepatcht, was noch nicht auf github lag, so dass es für den Moment keine Möglichkeit gab, die Änderungen zu bekommen... Vermutlich wäre das auch kein Problem, solange sich niemand beschwert?

**Comment by almereyda** [comment]
AGPL ist die beste Wahl für Websoftware, da sie explizit für SaaS geschaffen wurde.

Es wäre auch möglich eine CI/CD Pipeline für die Deployments zu bauen, sodass der Code immer schon verfügbar ist, bevor er ausgeführt wird.

Wenn ihr zeitweise auch mal von einem unveröffentlichten Branch lauft, würdet ihr tatsächlich eure eigene Lizenz verletzen, wenn ihr Lizenznehmer wäret. Da die Lizenz aber nur vom Inhaber des Urheberrechts erteilt werden kann, die ihr seid, steht es euch auch frei von diesem Gebrauch zu machen, d.h. die Bedingungen der Lizenz gelten dann nicht. Soweit meine Interpretation.

> ‘Modify’ is defined in the AGPL (as it is in GPLv3) as meaning to:
>
> “copy from or adapt all or part of the work in a fashion requiring copyright permission, other than the making of an exact copy.”
>
> https://www.kempitlaw.com/open-source-software-the-affero-gpl-the-as-a-service-world-and-the-cal/

**Comment by tvogel** [comment]
@timof @kinimo @eliasmagn Was meint Ihr dazu?

**Comment by tvogel** [comment]
Hab jetzt endlich die AGPL integriert!
