### ISSUE TITLE
Incorrect index name 'primary'

### ISSUE THREAD

**Issue by toblinga** [foodsoft/foodsoft#9]
```
ALTER TABLE catalogue_acronyms ADD UNIQUE KEY `primary` ( id );
```

=> primary ist ein reserved word (http://dev.mysql.com/doc/refman/5.1/de/reserved-words.html) und kann somit nicht als Key-Name verwendet werden.

**Comment by tvogel** [comment]
Äh, ich kann die angesprochene Code-Zeile gar nicht finden. Wo soll die sein? Kommt das aus eine Fork, von dem ich nichts weiß?

**Comment by toblinga** [comment]
ich hab in der structure.php für die Tabelle catalogue_acronyms stand folgendes 
  , 'indices' => array(
      'primary' => array( 'unique' => 1, 'collist' => 'id' )
    , 'secondary' => array( 'unique' => 1, 'collist' => 'context, acronym')

primary hab ich mit PRIMARY wie es auch bei allen anderen tabellen stand angepasst. das funktionierte.

bzgl. Code: hab die stable-version als zip downgeloades https://github.com/foodsoft/foodsoft/archive/stable.zip

Der Alter-Befehl kam nur daher, da ich manuell einen Key "prim" angelegt habe mit den gleichen Eigenschaften, um zu sehen ob es am key-word primary liegt.

**Comment by timof** [comment]
On Tue, Sep 10, 2013 at 11:25:10PM -0700, toblinga wrote:

> primary hab ich mit PRIMARY wie es auch bei allen anderen tabellen stand angepasst. das funktionierte.

ja, Grossschreibung PRIMARY ist hier tataechlich wichtig! danke, ist jetzt in
stable uebernommen.

Gruesse, Timo

**Comment by toblinga** [comment]
hab die änderung bei mir manuell gamacht nicht mit der neuen stable getestet. close es trotzem

Danke für die schnelle Reaktion!

LG
Armin
